
before_script:

stages:
  - test
  - stop

test_job:
  stage: test
  script:
    - ./start.sh
    - ./stop.sh
  only:
    - master

stop:
  stage: stop
  script:
    - ./stop.sh
  only:
    - master
  when: always
